### PR TITLE
Added some new themes

### PR DESCRIPTION
**Pull request by martijnonline**
- Two variations on the original theme (transparent & inverted).
- And a new countdown theme with 7 available colors

### CODE REVIEW

**Comment by pfarmer** [comment]
Hi,

Thanks for the new image sets, but the 8's on the new theme's are not quite right, they drop slightly.... Could you fix this? Also any chance you could do some smaller sets.

Thanks again,

Peter

**Comment by martijnonline** [comment]
I''ll look in to the 8's in the new set.

About smaller sets: isn't it easier to make a little tutorial on how to create smaller images? I presume everyone needs other dimensions.

Example: If you want the digits to be 25px \* 37px (keep the same proportions as original). You have to set the digitWidth to 25 and the digitHeight to 37 in the javascript. And the .png must be resized to 25px \* 2220px. The current .png's include 60 separate images (6 for each digit) a little calculation makes: 37*60=2220px. 

I'm also working on another design. I hope I can include a little fade-in and fade-out in this one.

**Comment by pfarmer** [comment]
Hi,

Just merged this to get the new themes out there, let me know once the 8 digits are fixed and your new theme is ready.

Thanks,

Peter

**Comment by martijnonline** [comment]
I will, but currently I'm busy with some personal projects.

**Pull request merged**
